### ISSUE TITLE
Telethon Version incompatibility error

### ISSUE THREAD

**Issue by timeisflowing** [jordanwildon/Telepathy#14]
The error he gave after logging in

`name = entity.title
AttributeError: 'User' object has no attribute 'title'`

**Telepathy** Version 2.0.0
**Telethon** Version 1.24.0

What are you using in the stable version of the telethon? 

can you share the requirements file to install a stable version of the libraries you use for telepathy?

**Comment by jordanwildon** [comment]
I believe this was fixed and I didn't close the issue, but will ensure that the version is specified in the new requirements.txt.
