### ISSUE TITLE
Entire account is missing

### ISSUE THREAD

**Issue by shadowdevnotreal** [jordanwildon/Telepathy#18]
Great idea but I ran your app 2x and it ran successfully, except it did not grab user list and my entire account is gone.
All saved messages, all my chats gone.

I was hunting pedophiles and there was private chats that are now just gone.
Absolutely no way for me to restore months of data.

I do not even know what to say at this point........

**Comment by jordanwildon** [comment]
Closing due to this being to do with an assumed Telegram ToS violation and not related to Telepathy. Therefore, this is something I have no control over. Please refer to the usage terms in README.md.
