### ISSUE TITLE
Missing option

### ISSUE THREAD

**Issue by pouling** [jordanwildon/Telepathy#19]
from latest documentation, we should be able to use -u for user, this option doesn't seem to be there

D:\telepathy\dump\Telepathy\telepathy>telepathy -u durov
Usage: telepathy [OPTIONS]
Try 'telepathy --help' for help.

Error: no such option: -u

D:\telepathy\dump\Telepathy\telepathy>telepathy --help
Usage: telepathy [OPTIONS]

Options:
  -t, --target TEXT    Specifies a chat to investigate.
  -c, --comprehensive  Comprehensive scan, includes archiving.
  -m, --media          Archives media in the specified chat.
  -f, --forwards       Scrapes forwarded messages.
  --help               Show this message and exit.

**Comment by jordanwildon** [comment]
This can be solved with an update. I'd recommend updating once 2.1.10 is live.
`$pip3 install --upgrade telepathy`
