### ISSUE TITLE
instal error

### ISSUE THREAD

**Issue by shanow7** [jordanwildon/Telepathy#23]
csi@csi:~/Desktop/OSINT$ git clone https://github.com/jordanwildon/Telepathy.git
Cloning into 'Telepathy'...
fatal: unable to access 'https://github.com/jordanwildon/Telepathy.git/': server certificate verification failed. CAfile: none CRLfile: none

can you help?

**Comment by jordanwildon** [comment]
How strange. Haven't been able to replicate this. Will check over things as I push out 2.1.10 and work on a fix if the problem persists.

**Comment by shanow7** [comment]
pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
ERROR: Invalid requirement: 'Telethon=1.24.0' (from line 6 of requirements.txt)
Hint: = is not a valid operator. Did you mean == ?

**Comment by jordanwildon** [comment]
Totally my fault. Rushed the update. Will fix when I get back home and in the meantime scream into the void.

Can be temporarily fixed by editing the requirements.txt to include “==“ instead of “=“ in all cases.
