### ISSUE TITLE
No module names 'libs.utils'

### ISSUE THREAD

**Issue by jonacarda** [jordanwildon/Telepathy#29]
Hi, I am having problem running the tool. I always the error of the image.

ModuleNotFoundError: No module named 'libs.utils'

Can anyone help me out?
thank you

**Comment by jonacarda** [comment]
![ff](https://user-images.githubusercontent.com/102680524/196711843-d453a8f3-761c-4386-a109-125ff4f0c649.png)

**Comment by jordanwildon** [comment]
Fixed! Just needed to change some setup files.
