### ISSUE TITLE
Love the tool! How about a CLI?

### ISSUE THREAD

**Issue by GrantRVD** [jordanwildon/Telepathy#3]
Love the suite of tools here, having just come from a role that featured quite a few investigations of Telegram. The scripts seem easy to use, but I bet they could be made even easier with a basically CLI around everything. I didn't see a `contributing.md` in the repo, so I figured I would ask here: would you be interested in me adding a `click` CLI wrapper around this? I haven't spec'd anything out, and I'm happy to do so - from what I see, I think it could be done in a weekend project.

**Comment by GrantRVD** [comment]
Great! Will set aside some time to look, perhaps as early as this weekend, and let you know if I run into any issues.

**Comment by jordanwildon** [comment]
Hey there, I spent some time recently looking into making this happen and have completed initial production of a CLI wrapper. Will shortly release it in an upcoming major update.
