### ISSUE TITLE
phone bot token

### ISSUE THREAD

**Issue by NattiB** [jordanwildon/Telepathy#38]

**Comment by NattiB** [comment]
sorry to be stupid. on set up everything is fine but i have encountered a problem where it is asking me for my phone (or bot token)? am i being stupid? i have done everything right it seems but now cant move on. can anyone advise?

**Comment by LessDigital13** [comment]
Hey! Check the Setup section: on first use you need to enter three different things:

- API id
- subsequent hash for they API
- the phone number associated with the Telegram account you're using

The tool won't work without all three.

**Comment by NattiB** [comment]
All sorted. Thank you for helping. Not sure what happened, i got sent a code in the end. take care
