### ISSUE TITLE
Unable to download v2.3.2

### ISSUE THREAD

**Issue by LessDigital13** [jordanwildon/Telepathy#39]
Really awesome tool, Jordan! I'm really excited to get to know/use it. I'm having an issue when running the setup where it only downloads/installs the v2.0.0 version. 

I think this is preventing the overall tool from running properly with the usage commands I input. 

Any suggestions?

*I'm extremely new to coding and OSINT - if this is a basic user error on my part, I apologize!*

**Comment by Andrejki** [comment]
Same here, and solved by upgrading the pip3 install option and then installing it via pip3. 

I can t install it from source. 
Well, this is a powerful tool, so I guess people are not that open to teach us newbies what we need to do.
