### ISSUE TITLE
I'm having some issues

### ISSUE THREAD

**Issue by JackOlwens** [jordanwildon/Telepathy#5]
File "/data/data/com.termux/files/home/Telepathy/telepathy.py", line 46, in <module>
    exec(open("members.py").read())
  File "<string>", line 64, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "/data/data/com.termux/files/usr/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/chats.py", line 474, in get_participants
    return await self.iter_participants(*args, **kwargs).collect()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/requestiter.py", line 113, in collect
    async for message in self:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/requestiter.py", line 74, in __anext__
    if await self._load_next_chunk():
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/chats.py", line 200, in _load_next_chunk
    results = await self.client(self.requests)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/telethon/client/users.py", line 75, in _call
    raise MultiError(exceptions, results, requests)
telethon.errors.common.MultiError: ([FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), None, None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), None, FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)'), FloodWaitError('A wait of 30 seconds is required (caused by GetParticipantsRequest)')], [None, <telethon.tl.types.channels.ChannelParticipants object at 0x732d18a7a0>, None, None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x732d188a00>, <telethon.tl.types.channels.ChannelParticipants object at 0x732d18a9b0>, None, None, None, <telethon.tl.types.channels.ChannelParticipants object at 0x732d18a6b0>, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None], [<telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d10b190>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d10b790>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d10bd90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d10be50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d10bf10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d10bfd0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d1140d0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114190>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114250>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114310>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d1143d0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114490>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114550>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114610>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d1146d0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114790>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114850>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114910>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d1149d0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114a90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114b50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114c10>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114cd0>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114d90>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114e50>, <telethon.tl.functions.channels.GetParticipantsRequest object at 0x732d114f10>])
Segmentation fault

Is there an issue on my side that I need to fix? I did a clean install and setup, can't figure out if there is something else.

**Comment by jordanwildon** [comment]
Just managed to replicate this. Seems to be an API issue. I'll work on trying to find a way around it.

**Comment by jordanwildon** [comment]
Managed to fix this and it looks like things are in working order now!

**Comment by JackOlwens** [comment]
Thanks!!!!!
